### ISSUE TITLE
Traitor / Detective Pass

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#10]
Please add Traitor / Detecitve Passes with Coins. If someone type !traitor he is in the next round to 100% Traitor.

**Comment by popey456963** [comment]
Preferably, some sort of command that could interface with other methods than coins, such as a generic sm_setTraitorNextRound.  That way we could still add it to a plugin to be bought with coins but *also* we could integrate it with external programs.

**Comment by good-live** [comment]
@popey456963 It should be easy to implement the commands with the new natives. However i haven't tested this yet. So it would be nice to get some feedback,

**Comment by popey456963** [comment]
@good-live I see both TTT_ForceTraitor and TTT_ForceDetective as being functions I can use, what exactly is their behavior when there are already enough traitors however?

**Comment by good-live** [comment]
They will get added to the force queue (if there aren't already part of it)
However there won't be more traitors then otherwise.
Exampel:
10 Players
30% Traitors = 3 Traitors
4 Players in the traitor queue.
Only the first 3 will become a Traitor.

Next Round:
The last one in the queue will become Traitor + 2 random Traitors.

(In theory, however this feature isn't tested yet)

**Comment by Bara20** [comment]
Added. If anyone has an issue on this, open a new issue.
