### ISSUE TITLE
Fake Body Bug

### ISSUE THREAD

**Issue by Bobakanoosh** [Bara20/TroubleinTerroristTown#102]
When a fake body is inspected, the players name still shows alive if you hit tab. This sort of (in my opinion) destroys part of the purpose of a fake body.

**Comment by Aura89** [comment]
If it showed them as dead, false KOS' would happen all the time due to "well there's 3 people left, i found this (fake) body, now there's 2 people left, lets kill eachother" nonsense. And then when that happens everyone would be freaking out saying the server must be broken because there's only one person left on the scoreboard and its not restarting the round.

If you don't like the way fake bodies are done i personally would recommend changing how they work, which you can do in the cfg file for fakebodies. For instance, on my server, it's set up that the bodies do not disappear and they do not state who it was that dropped the body. It simply states "so and so has found a fake body". This allows traitors to set traps, as well as since they do not change color when ID'd, it's possible that someone might KOS an innocent, within their rights, for "not IDing a body"

**Comment by Bobakanoosh** [comment]
You're very right, didn't think about that rdm bit.
