### ISSUE TITLE
Even With Public Karma Wait To Round End To Display

### ISSUE THREAD

**Issue by popey456963** [Bara20/TroubleinTerroristTown#60]
```
        "ttt_public_karma"
        {
                "value"         "1"
                "description"           "Show karma as points (or another way?)"
        }
        "ttt_private_karma_round_update"
        {
                "value"         "1"
                "description"           "If ttt_public_karma is not set to 1, enable this to update karma at end of round."
        }
```

I really like the public score based on karma, but I don't think I can justify it when people can just camp and hold tab to see who the traitor is.  Any way of having ttt_public_karma set to one but ALSO for it to only update at the end of a round?

**Comment by good-live** [comment]
Just set ttt_public_karma to 0 and you got what you want.

**Comment by popey456963** [comment]
` enable this to update karma at end of round.`

Thanks for the speedy reply and things, perhaps a better description would be useful?  Something like:

`If ttt_public_karma is 0, enable this to update karma at end of round, else if ttt_public_karma is 1, enable this to update karma instantly`

Although that also sounds really terrible.

**Comment by good-live** [comment]
If ttt_public_karma is enabled, then it doesnt matter what ttt_private_karma_round_update is set to.

**Comment by popey456963** [comment]
Ahh, now I've reread your comment and realised my error in communication.  I really enjoy ttt_public_karma and what I'm saying is I'd love to keep it but still only have it updated on round end so that people can't find out who the traitors are instantly.  At the moment it seems an either/or, update karma on round end OR have karma visible.

**Comment by good-live** [comment]
ttt_public_karma 1 = Karma on Scoreboard get's updated instantly.
ttt_public_karma 0 = Karma on Scoreboard doesn't get updated instantly.
ttt_private_karma_round_update 1 = Karma on Scoreboard get's updated on Round end.
ttt_private_karma_round_update 0 = Karma on Scoreboard doesn't get updated on Round end.

So when you have ttt_public_karma 1 then it doesn't matter what youve set ttt_private_karma_round_update to, because Karma get's updated instantly anyway.

You only wont have any Karma on Scoreboard, when you set both to 0.

**Comment by popey456963** [comment]
Oh, I am truly a fool.  Thanks for clearing that up!
