### ISSUE TITLE
Armor and Slow bug

### ISSUE THREAD

**Issue by Chickenw** [Bara20/TroubleinTerroristTown#63]
So when shooting someone before round start it takes all the armor away. The older one did not do this. Also it slows that person down a lot. If someone gets the m249 and walking down somewhere in a group he can slow ALL of them...
https://youtu.be/lRShhh4nW2Y

**Comment by popey456963** [comment]
:+1: I'm getting this issue too.  Another side effect that appears to be of whatever causes this is that it also causes the damage on kill message to be vastly out of scale (damage given: 19000, damage taken: 125, despite you not killing him because all of that damage was done in warmup).

Perhaps is there a way to disable damage and slow to a person by hooking the bullet hit event, it would mean you could still break things like windows but wouldn't be able to damage/slow people

**Comment by Chickenw** [comment]
Have notice that damage bug too where it says u do TONS of damage to someone but u never did lol

**Comment by Bara20** [comment]
Try this. Wait a bit for compiling

**Comment by Chickenw** [comment]
Thanks Bara ill run this and test:)

**Comment by Chickenw** [comment]
Working Great! fixed both of these problems
