### ISSUE TITLE
CLANTAG @Bara

### ISSUE THREAD

**Issue by kikoplg** [Bara20/TroubleinTerroristTown#68]
Wird nur beim Spawn und Role Vergabe neu gesetzt.

**Comment by popey456963** [comment]
Agree with this completely!  Preserving the usual clan tag unless the player is dead would be very useful.  It'd also be nice to have a function to get a players normal clan tag.  We give players benefits based on clan tags which currently doesn't work on TTT because you change the clantag to nothing on round start :)

My imagination would be:

 - Round start, reset to default player clan tag
 - Guy dies, change their clan tag to Innocent/Traitor/Detective
 - On round end, all clan tags are changed to their specific role
 - On round start, all clan tags are reset to default, cycle repeats.

**Comment by kikoplg** [comment]
TTT Runde inaktiv -> Alle die bereits gespawnt sind und alle die während den 30 Sekunden joinen sind tot und haben KEINEN Clantag.

TTT Runde aktiv -> Alle lebenden ausser der Dete KEINEN Clantag, alle toten, welche geprüft (E push) wurden haben den jeweiligen Teamtag und sind tot. Alle die während einer aktiven TTT Runde joinen sind tot und haben einen unassigned Clantag.

**Comment by Bara20** [comment]
https://github.com/Bara20/TroubleinTerroristTown/commit/c1b8a9fc831e3be63319e0d942db0676b5d5cc81

**Comment by kikoplg** [comment]
FIXED - TY
